version: '3.1'

services:
  db:
    image: postgres:10.6-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: praesidiume
      POSTGRES_DB: praesidiume

  cache:
    image: redis:5-alpine
    ports:
      - '6379:6379'
    restart: always
